categories: Categories
search: Search
tags: 所有标签
tagcloud: "Tag Cloud"
prev: Prev
next: Next
comment: Comments
contents: Contents
archive_a: Archives
archive_b: "Archives: %s"
page: "Page %d"
recent_posts: "Recent Posts"
menu: Menu
links: 最近文章
rss: RSS
showsidebar: "Show Sidebar"
hidesidebar: "Hide Sidebar"
updated: Updated
